moved scripts into "linux" to ease packaging

diff --git a/linux/bin/arduino-launch b/linux/bin/arduino-launch
--- a/linux/bin/arduino-launch
+++ b/linux/bin/arduino-launch
@@ -4,27 +4,31 @@
 BIN_ABSPATH=$(cd "$(dirname "$0")"; pwd)
 
 # resolving messages folder path
-MESSAGES_ABSPATH=$BIN_ABSPATH/../messages
+PROCESSES_ABSPATH=$BIN_ABSPATH/../processes
 
-# Retrieve handle and command
+# Retrieve handle and remove it from the params
 HANDLE=$1
-COMMAND=$2
+shift
 
-# removing handle and command from the list of params
-shift 2
+# Making folder for this process outputs and 
+BASEDIR=$PROCESSES_ABSPATH/$HANDLE
+mkdir $BASEDIR
 
-# files to hold stdout and stderr output generated by running command
-TMP_OUT=`mktemp`
-TMP_ERR=`mktemp`
+OUT_FILE=$BASEDIR/stdout
+ERR_FILE=$BASEDIR/stderr
+IN_FILE=$BASEDIR/stdin
+PID_FILE=$BASEDIR/running
+EXITCODE_FILE=$BASEDIR/exit_code
 
-# executing command
-COMPLETE_COMMAND="$COMMAND $*"
-($COMPLETE_COMMAND) 1>$TMP_OUT 2>$TMP_ERR
-EXIT_CODE=$?
+$* > $OUT_FILE 2> $ERR_FILE &
+PID=$!
 
-# creating messages files
-MESSAGE_FILE=`date +%s`
-MESSAGE_FILE="$MESSAGE_FILE-$COMMAND-$HANDLE"
+# Save the process number
+echo $PID > $PID_FILE
 
-mv $TMP_OUT $MESSAGES_ABSPATH/$MESSAGE_FILE.out
-mv $TMP_ERR $MESSAGES_ABSPATH/$MESSAGE_FILE.err
+# Wait for process termination
+wait $PID
+
+# Save the exit code
+echo $? > $EXITCODE_FILE
+rm -f $PID_FILE
